import React,{useEffect,useState} from 'react'
import axios from 'axios'
import {Link,useNavigate,useParams} from 'react-router-dom'
import {useCartStore} from '../stores/cartStore.js'
axios.defaults.withCredentials=true
const api='http://localhost:3000'
const image=(p)=>`${api}/img_pd/${p?.pdId}.jpg`
function ProductGrid(){const [items,setItems]=useState([]),[error,setError]=useState('');useEffect(()=>{axios.get(`${api}/products`).then(r=>setItems(Array.isArray(r.data)?r.data:r.data.products||[])).catch(()=>setError('โหลดสินค้าไม่สำเร็จ กรุณาตรวจสอบว่า backend เปิดอยู่'))},[]);return <div className="container py-4"><h2 className="mb-4">สินค้า</h2>{error&&<div className="alert alert-warning">{error}</div>}<div className="row g-3">{items.map(p=><div className="col-6 col-md-4 col-lg-3" key={p.pdId}><div className="card h-100 shadow-sm"><img className="card-img-top product-img p-2" src={image(p)} onError={e=>e.currentTarget.style.visibility='hidden'} alt={p.pdName}/><div className="card-body"><h5>{p.pdName}</h5><p>{Number(p.pdPrice||0).toLocaleString()} ฿</p><Link className="btn btn-success" to={`/ProductShow/${p.pdId}`}>ดูสินค้า</Link></div></div></div>)}</div></div>}
export function MainMenu(){const [member,setMember]=useState(null);const cart=useCartStore();const nav=useNavigate();const refresh=()=>axios.get(`${api}/members/detail`).then(r=>setMember(r.data)).catch(()=>setMember(null));useEffect(()=>{refresh()},[]);async function logout(){try{await axios.get(`${api}/members/logout`)}finally{setMember(null);nav('/')}}return <nav className="navbar navbar-expand-lg navbar-dark bg-success"><div className="container"><Link className="navbar-brand" to="/">I HAVE KU</Link><div className="navbar-nav me-auto"><Link className="nav-link" to="/">สินค้า</Link><Link className="nav-link" to="/cartList">ตะกร้าของฉัน</Link>{member?.role==='admin'&&<><Link className="nav-link" to="/admin/members">สมาชิก</Link><Link className="nav-link" to="/admin/addproducts">เพิ่มสินค้า</Link></>}</div><div className="navbar-nav">{member?<><Link className="nav-link" to="/pagemember">{member.memName||member.memEmail}</Link><button className="btn btn-outline-light btn-sm" onClick={logout}>ออกจากระบบ</button></>:<><Link className="nav-link" to="/login">เข้าสู่ระบบ</Link><Link className="nav-link" to="/register">สมัครสมาชิก</Link></>}</div></div></nav>}
export function TheProduct(){return <ProductGrid/>}
export function TheLogin(){const nav=useNavigate(),[form,set]=useState({loginName:'',password:''}),[msg,sm]=useState('');async function submit(e){e.preventDefault();try{const r=await axios.post(`${api}/members/login`,form);sm(r.data.message||'เข้าสู่ระบบสำเร็จ');if(r.data.login)nav('/')}catch(e){sm(e.response?.data?.message||'เข้าสู่ระบบไม่สำเร็จ')}}return <div className="login-container"><form className="login-card" onSubmit={submit}><h2 className="mb-4">เข้าสู่ระบบ</h2>{msg&&<div className="alert alert-info">{msg}</div>}<label className="form-label">อีเมล</label><input className="form-control mb-3" value={form.loginName} onChange={e=>set({...form,loginName:e.target.value})} required/><label className="form-label">รหัสผ่าน</label><input className="form-control mb-3" type="password" value={form.password} onChange={e=>set({...form,password:e.target.value})} required/><button className="btn btn-success w-100">เข้าสู่ระบบ</button><p className="mt-3">ยังไม่มีบัญชี? <Link to="/register">ลงทะเบียน</Link></p></form></div>}
export function TheRegister(){const [form,set]=useState({memEmail:'',memName:'',password:''}),[msg,sm]=useState('');async function submit(e){e.preventDefault();try{const r=await axios.post(`${api}/members`,form);sm(r.data.message||'ลงทะเบียนสำเร็จ')}catch(e){sm(e.response?.data?.message||'ลงทะเบียนไม่สำเร็จ')}}return <div className="container py-5" style={{maxWidth:600}}><form className="card card-body" onSubmit={submit}><h2>ลงทะเบียนสมาชิกใหม่</h2>{msg&&<div className="alert alert-info">{msg}</div>}{[['memEmail','อีเมล','email'],['memName','ชื่อ-นามสกุล','text'],['password','รหัสผ่าน','password']].map(([k,l,t])=><div className="mb-3" key={k}><label className="form-label">{l}</label><input className="form-control" type={t} required value={form[k]} onChange={e=>set({...form,[k]:e.target.value})}/></div>)}<button className="btn btn-primary">ลงทะเบียน</button><p className="mt-3">มีบัญชีแล้ว? <Link to="/login">เข้าสู่ระบบ</Link></p></form></div>}
export function ProductShow(){const {pdId}=useParams(),[p,set]=useState(null),cart=useCartStore();useEffect(()=>{axios.get(`${api}/products/${pdId}`).then(r=>set(Array.isArray(r.data)?r.data[0]:r.data))},[pdId]);async function add(){try{const m=await axios.get(`${api}/members/detail`);let c=await axios.post(`${api}/carts/chkcart`,{memEmail:m.data.memEmail});let id=c.data.cartId;if(!id){const created=await axios.post(`${api}/carts/addcart`,{cusId:m.data.memEmail});id=created.data.messageAddCart}const added=await axios.post(`${api}/carts/addcartdtl`,{cartId:id,pdId,pdPrice:p.pdPrice});if(!added.data.cartDtlOK)throw new Error();cart.setId(id);cart.updateQty();alert('เพิ่มสินค้าในตะกร้าแล้ว')}catch{alert('กรุณาเข้าสู่ระบบก่อนเพิ่มสินค้า')}}if(!p)return <div className="container py-5">กำลังโหลดสินค้า...</div>;return <div className="container py-5"><div className="row"><div className="col-md-6"><img className="img-fluid" src={image(p)} alt={p.pdName}/></div><div className="col-md-6"><h2>{p.pdName}</h2><p>{p.pdRemark}</p><h4>{Number(p.pdPrice||0).toLocaleString()} ฿</h4><button className="btn btn-success" onClick={add}>เพิ่มลงตะกร้า</button></div></div></div>}
export function CartShow(){const {cartId}=useParams();return <CartPage id={cartId}/>}
export function CartPage({id}){const [rows,set]=useState([]);useEffect(()=>{if(id)axios.get(`${api}/carts/getcartdtl/${id}`).then(r=>set(Array.isArray(r.data)?r.data:[])).catch(()=>{})},[id]);return <div className="container py-5"><h2>ตะกร้าสินค้า {id&&`#${id}`}</h2>{rows.length?rows.map((x,i)=><div className="card card-body mb-2" key={i}>{x.pdName||x.pdId}　จำนวน {x.qty}　ราคา {x.pdPrice} ฿</div>):<p>ยังไม่มีสินค้าในตะกร้า</p>}<Link to="/">เลือกซื้อสินค้า</Link></div>}
export function CartList(){const [rows,set]=useState([]);useEffect(()=>{axios.get(`${api}/members/detail`).then(r=>axios.post(`${api}/carts/getcartbycus`,{id:r.data.memEmail})).then(r=>set(Array.isArray(r.data)?r.data:[])).catch(()=>{})},[]);return <div className="container py-5"><h2>รายการตะกร้าสินค้า</h2>{rows.length?rows.map((r,i)=><div className="card card-body mb-2" key={i}><Link to={`/cartShow/${r.cartId}`}>ตะกร้า #{r.cartId}　{r.cartCf?'ยืนยันแล้ว':'กำลังเลือกสินค้า'}　{r.sqty||0} รายการ</Link></div>):<p>ไม่พบรายการตะกร้า</p>}</div>}
export function PageMember(){const [m,set]=useState(null);useEffect(()=>{axios.get(`${api}/members/detail`).then(r=>set(r.data)).catch(()=>{})},[]);return <div className="container py-5"><h2>ข้อมูลสมาชิก</h2>{m?<div className="card card-body"><p>อีเมล: {m.memEmail}</p><p>ชื่อ: {m.memName}</p></div>:<p>กรุณาเข้าสู่ระบบ</p>}</div>}
export function ListMemberShow(){const [items,set]=useState([]);useEffect(()=>{axios.get(`${api}/members/all`).then(r=>set(Array.isArray(r.data)?r.data:[])).catch(()=>{})},[]);return <div className="container py-5"><h2>สมาชิก</h2><div className="table-responsive"><table className="table"><thead><tr><th>อีเมล</th><th>ชื่อ</th><th>สิทธิ์</th></tr></thead><tbody>{items.map((m,i)=><tr key={i}><td>{m.memEmail}</td><td>{m.memName}</td><td>{m.role}</td></tr>)}</tbody></table></div></div>}
export function AddProduct(){const [form,set]=useState({pdId:'',pdName:'',pdPrice:'',pdRemark:'',pdTypeId:'',brandId:''}),[file,sf]=useState(null),[msg,sm]=useState('');async function submit(e){e.preventDefault();try{await axios.post(`${api}/products`,form);if(file){const d=new FormData();d.append('pdId',form.pdId);d.append('file',file);await axios.post(`${api}/products/uploadimg`,d)}sm('เพิ่มสินค้าสำเร็จ')}catch(e){sm(e.response?.data?.message||'เพิ่มสินค้าไม่สำเร็จ')}}return <div className="container py-5" style={{maxWidth:850}}><form className="card card-body" onSubmit={submit}><h2>เพิ่มสินค้าใหม่</h2>{msg&&<div className="alert alert-info">{msg}</div>}{[['pdId','รหัสสินค้า'],['pdName','ชื่อสินค้า'],['pdPrice','ราคา'],['pdTypeId','รหัสประเภทสินค้า'],['brandId','รหัสแบรนด์']].map(([k,l])=><div className="mb-3" key={k}><label className="form-label">{l}</label><input className="form-control" required value={form[k]} onChange={e=>set({...form,[k]:e.target.value})}/></div>)}<label className="form-label">รายละเอียด</label><textarea className="form-control mb-3" value={form.pdRemark} onChange={e=>set({...form,pdRemark:e.target.value})}/><input type="file" accept="image/*" className="form-control mb-3" onChange={e=>sf(e.target.files[0])}/><button className="btn btn-success">บันทึกสินค้า</button></form></div>}
